swagger: "2.0"
info:
  title: service.proto
  version: version not set
tags:
  - name: TestService
consumes:
  - application/json
produces:
  - application/json
paths:
  /test:
    get:
      summary: The description of the method
      operationId: TestService_Test
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/TestResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - TestService
      security:
        - Bearer: []
    post:
      summary: The description of the method
      operationId: TestService_ReceiveName
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/TestResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          description: TestRequestWithName is the request message for the ReceiveName method.
          in: body
          required: true
          schema:
            $ref: '#/definitions/TestRequestWithName'
      tags:
        - TestService
definitions:
  TestRequestWithName:
    type: object
    properties:
      name:
        type: string
        description: Name is the name of the person.
    description: TestRequestWithName is the request message for the ReceiveName method.
  TestResponse:
    type: object
    properties:
      message:
        type: string
        description: Message is the test message.
    description: TestResponse is the response message for the Test method.
    required:
      - message
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
securityDefinitions:
  Bearer:
    type: apiKey
    description: Bearer Token
    name: Authorization
    in: header
